baseURL = 'https://hamsterthon.github.io/'
languageCode = 'en-us'
title = 'Hamsterthon'
theme = 'ananke'

[markup.goldmark.renderer]
unsafe = true

[params]

    [[params.ananke_socials]]
        name = 'github'
        url = 'https://github.com/hamsterthon'

